### ISSUE TITLE
Organization tips

### ISSUE THREAD

**Issue by sr320** [jldimond/fish546-2015#3]
In Readme explain what you use each directory for.
https://github.com/jldimond/fish546-2015/blob/master/README.md

Data directory does not have those directories..

I suggest analyses going in Analyses directory and keeping raw data separate.

**Comment by jldimond** [comment]
Maybe I should have individual directories for each species that each have data, analysis, nb, and scripts directories? By the way, what do you see as the difference between a scripts and nb directory?

**Comment by sr320** [comment]
Sure that would be fine.

I place bash/perl/python scripts that I might have to call on in my
notebook in script directory.
ie
https://github.com/sr320/eimd-sswd/tree/master/scripts

**Comment by jldimond** [comment]
Thanks for the clarification. Not sure I will change directory structure, but will think about it.

On another note, I seem to have lost the link to the Bioinformatics text book--can you direct me to it?

**Comment by sr320** [comment]
https://plus.google.com/u/0/106492099842577316500/posts/MaueUov69No

**Comment by jldimond** [comment]
Thanks!
